# Your workflow name.
name: Deploy to heroku.

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: npm ci && npm test
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: "123"
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web